on:
  push:
    paths: ['edx-harvardx-data-science-movielens-report.Rmd']

name: render-report

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::tidyverse

      - name: Install Required Packages
        run: Rscript -e 'install.packages(c("rmarkdown"))'
      
      - name: Render Rmarkdown and Commit Results
        run: |
          Rscript -e 'rmarkdown::render("edx-harvardx-data-science-movielens-report.Rmd", output_format = "all")'
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add edx-harvardx-data-science-movielens-report.pdf || echo "WARN: edx-harvardx-data-science-movielens-report.pdf was not updated"
          git commit -m 'Re-build Rmarkdown' || echo "No changes to commit"
          git push origin || echo "No changes to commit"